status: true
dependencies:
  config:
    - field.storage.paragraph.field_title
    - paragraphs.paragraphs_type.file_link_text
id: paragraph.file_link_text.field_title
field_name: field_title
entity_type: paragraph
bundle: file_link_text
label: Texto
description: 'Texto descriptivo del enlace.'
required: true
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
